packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@radix-ui/react-icons": "^1.3.2"
  "@testing-library/jest-dom": "^6.9.1"
  "@testing-library/react": "^16.3.2"
  "@types/node": "^24.10.11"
  "@types/react": "^19.2.13"
  "@types/react-dom": "^19.2.3"
  "@vitest/coverage-v8": "^4.0.18"
  "class-variance-authority": "^0.7.1"
  "dotenv": "^17.2.3"
  "jsdom": "^28.0.0"
  "lucide-react": "^0.563.0"
  "react": "^19.2.4"
  "react-dom": "^19.2.4"
  "react-hook-form": "^7.71.1"
  "tailwindcss": "^4.1.18"
  "typescript": "^5.9.3"
  "vitest": "^4.0.18"
